// <auto-generated />
namespace Fiap.Projeto.Web.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rm));
        
        string IMigrationMetadata.Id
        {
            get { return "201612160127178_Rm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
