//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverflowedStack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resposta
    {
        public int Id { get; set; }
        public int PerguntaId { get; set; }
        public int Autor { get; set; }
        public int AlunoRm { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Pergunta Pergunta { get; set; }
    }
}
